export const formCategoryOptions = [
  "Spielplatz",
  "Indoor Spielplatz",
  "Spielen",
  "Sport",
  "Sportplatz",
  "Sporthalle",
  "Sporthalle",
  "Sportkurs",
  "Klettern",
  "Skaten",
  "Wintersport",
  "Schwimmbad",
  "Freibad",
  "Badesee",
  "Strand & Meer",
  "Park",
  "Wald",
  "Kultur",
  "Musik",
  "Kunst",
  "Zirkus",
  "Basteln",
  "Essen & Trinken",
  "Übernachtung",
  "Freizeitpark",
  "Jahrmarkt",
  "Zoo",
  "Tiere",
  "Bauernhof",
  "Ponyreiten",
  "Sonstiger Spot",
];
