export const spotsList = [
  {
    id: "6c0fd517-8fc5-49ba-95ea-fc229d2071f9",
    category: "Spielplatz",
    name: "Baschu",
    addresse: "Schulterblatt 58B, 20357 Hamburg",
    weathersuggestion: ["bei gutem Wetter", "bei mäßigem Wetter"],
    agesuggestion: ["Kinder 1 - 3 Jahre", "Kinder 3 - 6 Jahre"],
    tags: ["seilbahn", "rutsche", "klettern"],
    information:
      "Der Baschu ist ein großer Hinterhof-Spielplatz, der von außen nicht zu entdecken ist, also ein echter Insider-Tipp und durch seine Hinterhof-Lage herrscht eine sehr familiäre Athmospäre",
    isFavorite: false,
  },
  {
    id: "a3ce28bb-2b52-4bc2-9799-4ec100075f12",
    category: "Spielplatz",
    name: "Brockmannsweg",
    addresse: "Brockmannsweg 5, 20146 Hamburg",
    weathersuggestion: ["bei gutem Wetter", "bei mäßigem Wetter"],
    agesuggestion: ["Kinder 1 - 3 Jahre", "Kinder 3 - 6 Jahre"],
    tags: ["rutsche", "schaukel"],
    information:
      "Vormittags Mo - Fr sehr voll durch zwei Kitas, ansonsten ein kleiner aber feiner Spieplatz, wo sich die direkte Nachbarschaft täglich trifft",
    isFavorite: false,
  },
  {
    id: "e3d4613b-6807-4d93-9637-6963d7b31ce1",
    category: "Indoor Spielplatz",
    name: "rabatzz!",
    addresse: "Kieler Str. 575a, 22525 Hamburg",
    weathersuggestion: ["bei schlechtem Wetter"],
    agesuggestion: [
      "Kinder 3 - 6 Jahre",
      "Kinder 6 - 9 Jahre",
      "Kinder 9 - 12 Jahre",
    ],
    tags: ["indoor", "trampolin", "rutschen"],
    information:
      "Indoor-Spaß für Groß und Klein! Weitere Infos unter: https://www.rabatzz.de/",
    isFavorite: false,
  },
  {
    id: "f1c6833e-d3f1-478a-ba5a-a3a5fbc37f8f",
    category: "Sportplatz",
    name: "ETV Fußball",
    addresse: "Bundesstraße 96, 20144 Hamburg",
    weathersuggestion: ["bei gutem Wetter", "bei mäßigem Wetter"],
    agesuggestion: ["Kinder 6 - 9 Jahre", "Kinder 9 - 12 Jahre", "Jugendliche"],
    tags: ["fußball", "kicken", "verein"],
    information:
      "Der Eimsbüttler Turnverein ist insbesondere bekannt, durch seine erfolgreichen Kinder- und Jugendmannschaften im Fußball. Weitere Infos und weiteres Spotangebot unter: https://etv-hamburg.de/",
    isFavorite: false,
  },
  {
    id: "9d331e98-0e51-488d-bf42-e52e4921683d",
    category: "Wald",
    name: "Forst Klövensteen",
    addresse: "Sandmoorweg 160, 22559 Hamburg",
    weathersuggestion: ["bei gutem Wetter", "bei mäßigem Wetter"],
    agesuggestion: [
      "Kinder 3 - 6 Jahre",
      "Kinder 6 - 9 Jahre",
      "Kinder 9 - 12 Jahre",
    ],
    tags: ["natur"],
    information:
      "Der Forst Klövensteen ist ein stadtnahes Forstgebiet, wo Familien vielerlei Aktivitäten unternehmen können von Ponyreiten in der kleinen Ponywaldschänke über eine tolle Inline-Skating-Tour oder ein Waldspaziergang zum Erforschen der Natur. Weitere Infos unter: https://www.hamburg.de/altona/forst-kloevensteen/",
    isFavorite: false,
  },
  {
    id: "1878ac77-442d-44fb-b984-cf7d2b7ac530",
    category: "Wintersport",
    name: "Skihalle Wittenburg",
    addresse: "Zur Winterwelt 1, 19243 Wittenburg",
    weathersuggestion: ["bei schlechtem Wetter"],
    agesuggestion: [
      "Kinder 3 - 6 Jahre",
      "Kinder 6 - 9 Jahre",
      "Kinder 9 - 12 Jahre",
      "Jugendliche",
    ],
    tags: ["ski", "snowboard", "schlitten"],
    information:
      "Indoor-Skihalle für Ski-Anfänger und -Fortgeschrittene. Ausrüstung kann vor Ort ausgeliehen werden. Weitere Infos unter: https://www.alpincenter.com/hamburg-wittenburg/de/skihalle",
    isFavorite: false,
  },
  {
    id: "17b711c7-1e9e-4f42-a281-7d795b8d8767",
    category: "Freibad",
    name: "Kaifu Bad",
    addresse: "Hohe Weide 15, 20259 Hamburg",
    weathersuggestion: ["bei gutem Wetter"],
    agesuggestion: [
      "Kinder 1 - 3 Jahre",
      "Kinder 3 - 6 Jahre",
      "Kinder 6 - 9 Jahre",
      "Kinder 9 - 12 Jahre",
      "Jugendliche",
    ],
    tags: ["schwimmen", "sprungturm", "sommer", "abkühlung"],
    information:
      "Das Freibad hat nur im Sommer auf, ist immer recht voll mit längerer Schlange am Seiteneingang. Weitere Infos: https://www.baederland.de/baeder/standorte/kaifu-bad/",
    isFavorite: false,
  },
];
